"""Executive summary: render actual expanded results with provenance and all stability tables."""
from .core import *

def table(frame):
 def cell(x):
  if x is None or (isinstance(x,float) and not np.isfinite(x)):return 'N/A'
  return f'{x:.6f}' if isinstance(x,(float,np.floating)) else str(x)
 lines=['| '+' | '.join(map(str,frame.columns))+' |','| '+' | '.join(['---']*len(frame.columns))+' |']
 lines += ['| '+' | '.join(cell(v) for v in row)+' |' for row in frame.itertuples(index=False,name=None)]
 return '\n'.join(lines)
def report():
 decision=json.loads((OUT/'final_decision.json').read_text());spec=json.loads((OUT/'experiment_spec.json').read_text());canonical=json.loads((OUT/'canonical_ledger_manifest.json').read_text());null=json.loads((OUT/'null_summary.json').read_text())['universes'];bs=json.loads((OUT/'bootstrap_summary.json').read_text());conc=json.loads((OUT/'concentration_summary.json').read_text());pert=json.loads((OUT/'baseline_perturbation_audit.json').read_text());oracle=json.loads((OUT/'oracle_summary.json').read_text());u0=json.loads((OUT/'u0_metrics.json').read_text());u1=json.loads((OUT/'u1_metrics.json').read_text())
 lines=['## Executive summary (read this first)','',f"Expanded audit: **{decision['PRICE_STATE_INFO03_EXPANDED_RESULT']}**. Exactly one next axis: **{decision['NEXT']}**. Source provenance remains PIT C; scoring it as a research sensitivity does not prove immutable historical availability or alpha.",'','This is the user-approved 2026-10-08 extension of the completed original PRICE-STATE03 study. Original PRE/result/specification/report remain unchanged. Original verdict INCONCLUSIVE and next V5.1-CENTER-BIAS-AUDIT-04 are historical facts, not replaced retroactively. All outcomes were already research-exposed through prior LOCATION01 and center-bias work. No independent OOS, official submission or new magnitude model.','',f"Parent RESULT {PARENT}; prior PRICE03 RESULT {PRIOR}; expanded PRE {decision['PRE_RESULT_PRICE_STATE_INFO03_SHA']}.",'','## Canonical source eligibility','',json.dumps(canonical,indent=2),'','Original canonical LOCATION01 no-text numeric V5.1 research distributions are reused. They are not a remeasurement of official V5.1-text Development0.9541. All primary ratios use matching cells and original past-only normalization. Fixed14 only exists in the inherited current-vintage2014–2024 file; early canonical folds lack training source history. No favorable later fold was newly selected.','',table(pd.read_csv(OUT/'fold_manifest.csv')),'','## Exact feature definition','',', '.join(NAMES),'','Exactly inherited weekday reindex/ffill(limit3), levels,5/21/63weekday differences and2s5s/2s10s. Primary broad asset one-hot encoding and log horizon fixed before labels. Numerical StandardScaler uses training rows only. C1, lbfgs, intercept, no weighting, threshold.50; translation always.05SD. No magnitude or probability calibration.','']
 for u,summary in [('U0',u0),('U1',u1)]:
  lines += [f'## {u} matched comparison','',table(pd.DataFrame([dict(Model=n,**v) for n,v in summary['models'].items()])),'',f"All {summary['cells']} cells / {summary['origins']} origins; assets {summary['assets']}; years {summary['years']}; folds {summary['evaluation_folds']}.",'','Weighting diagnostics:',json.dumps(summary['weightings'],indent=2),'']
 lines += ['## Null comparison','',json.dumps(null,indent=2),'','Matched-random preserving overall sign prevalence, fold-matched signs and exact balanced signs are different nulls. The original inherited MATCHED_RANDOM matched SEP positive frequency, not PRICE_LOGISTIC. Labels are permuted only in matured training folds. N3 reorders quarter sequences within train asset/horizon. N4 earlier-source donor resampling is non-exchangeable; its Monte Carlo tail fraction is descriptive, not an exact randomization test. N5 retains structural covariates and replaces14 price columns with Gaussian origin-level vectors. N8 is NOT_AVAILABLE, not fabricated. Plus-one p-values are diagnostic and do not certify independent OOS.','', '## Baseline perturbation','',json.dumps(pert,indent=2),'','Exact symmetric expected CRPS obeys location convexity: averaging+/-fixed shifts cannot improve individual expected loss. A finite balanced assignment can fluctuate; positive-prevalence matching can exploit exposed center bias. Constant+, constant-, and full distributions are retained; no best perturbation becomes a candidate.','']
 for title,file in [('All annual years','year_results.csv'),('All horizons','horizon_results.csv'),('All assets','asset_results.csv'),('Existing feature families','family_ablation.csv'),('Confidence and sign partitions','confidence_bin_summary.csv'),('Probability calibration','calibration_bins.csv')]:
  lines += ['## '+title,'',table(pd.read_csv(OUT/file)),'']
 lines += ['## Self price versus global rate state','',table(pd.read_csv(OUT/'self_vs_global_price_state.csv')),'','Family nulls match the corresponding frozen family prediction prevalence; families are diagnostics and cannot replace fixed14. SELF_PRICE/VOL_STATE are exact pre-existing canonical own-history values; no new price indicator was invented. No family combination, lag selection or favorable subset was fitted. Existing5/21/63price states are inventoried; standalone lag-model performance from the original study remains exposed descriptive evidence, not a new candidate.','', '## Concentration and block uncertainty','',json.dumps(conc,indent=2),'',json.dumps(bs,indent=2),'','Block uncertainty conditions on fixed fitted predictions; overlapping horizons, macro shocks, few chronological folds and limited evaluation years remain. No IID cell inference. All bad years/assets/horizons remain.','', '## Same-ledger oracle','',json.dumps(oracle,indent=2),'','The perfect location oracle is future-informed mathematical headroom, not evidence of predictable alpha.','', '## PIT and direct conclusion','', 'Only C fixed14 history is available; historical corrections cannot be bounded. A source-date lag solves early activation, not vintage revisions. No stronger vintage was manufactured, downloaded as a substitute, or inferred from frozen artifact hashes. PIT sensitivity comparison is NOT_AVAILABLE. The precommitted provenance gate therefore prevents a historical price-alpha claim, even when a direction statistic looks positive.','', 'The original0.993183 result alone does not establish price information. The original majority comparator scored0.989829. The expanded matched-null, bias, concentration and transfer tables above distinguish descriptive ranking evidence from useful incremental forecasting evidence. A public-source vintage recovery is required before validated conclusions.','', '## Verdict and next axis','',f"**{decision['PRICE_STATE_INFO03_EXPANDED_RESULT']}**; exactly **{decision['NEXT']}**. Next study not executed. V5.1 source, parent studies, baseline caches and existing submission artifacts are protected. Official0.9541 retained without remeasurement. No submission.",'','## Tests and recovery','', 'Ordered research/affected/full/common test results, protection hashes and remotely verified RESULT are bound by execution_audit.json and external recovery receipt. Private targets, draws, raw center errors and cell losses remain outside public Git. The ZIP must pass CRC, all-member SHA-256 and full archive SHA-256 before completion.']
 path=ROOT/'PRICE-STATE-INFORMATION-AUDIT-03-expanded-20261008-report.md';path.write_text('\n'.join(lines)+'\n');status('REPORT_COMPLETE',path);print('REPORT',path,flush=True)
if __name__=='__main__':report()
