"""Executive summary: public aggregate report; private per-cell results remain private."""
import json,platform,subprocess
import pandas as pd
from .core import *

def table(frame,columns=None):
 f=frame if columns is None else frame[columns];out=['| '+' | '.join(map(str,f.columns))+' |','|'+'|'.join(['---']*len(f.columns))+'|']
 for row in f.itertuples(index=False,name=None):out.append('| '+' | '.join(f'{v:.6f}'if isinstance(v,(float,np.floating))else str(v)for v in row)+' |')
 return '\n'.join(out)
def report():
 verify();read=lambda n:json.loads((OUT/n).read_text());parts=['## Executive summary (read this first)','This audit tests whether past V5.1 center errors predicted later bias. All original distributions and all parent files remain byte-frozen. Every location correction is RESEARCH_DIAGNOSTIC_ONLY; no submission or new production model.','All 2001–2024 outcomes are already exposed. PRE prevents within-experiment redesign but creates no independent OOS evidence. Original LOCATION01 forecasts are no-text V5.1 continuous research distributions, not an official re-evaluation of the V5.1-text submission package. Ratios use original research normalization and shared qfbench2-common CRPS.','Verdict: **'+read('final_decision.json')['V51_BIAS04_RESULT']+'**. Exactly one next axis: **'+read('next_axis_decision.json')['NEXT']+'**.']
 m=read('canonical_ledger_manifest.json');parts+=['## Reproduction and ledger',f"Parent narrow result reproduced exactly:52 origins,482cells; positive64.107884%; constant-up0.989828626, down1.011269077. Full canonical ledger:{m['origins']}origins,{m['cells']}cells,{len(m['assets'])}assets,{m['years']}years ({m['date_range']}). All1251 original caches verified against inherited SHA-256; last cache has no eligible target. No new origin selection, asset selection or target semantics.", 'Levels retain original future endpoint. Factor/Equity accumulated daily log-return targets retain original sum semantics. Horizons are5/21/63/126/189 calendar business days; targets mature by2024-12-18. Pooled raw errors mix incompatible units and are descriptive; standardized errors are more comparable.','## Balanced bias']
 wb=read('balance_weighting_summary.json')['summaries'];parts.append(table(pd.DataFrame([dict(weighting=k,**v)for k,v in wb.items()]),['weighting','positive_fraction','mean_raw_error','median_raw_error','mean_standardized_error','median_standardized_error']))
 for title,file,key in [('Year bias','year_bias_summary.csv','year'),('Era bias','era_bias_summary.csv','era'),('Asset-group bias','asset_group_bias_summary.csv','asset_group'),('Horizon bias','horizon_bias_summary.csv','horizon'),('Asset bias','asset_bias_summary.csv','asset')]:parts+=['## '+title,table(pd.read_csv(OUT/file),[key,'cells','positive_fraction','mean_raw_error','median_raw_error','mean_standardized_error','median_standardized_error'])]
 parts+=['All125 asset×horizon groups are retained in asset_horizon_bias_matrix.csv. Stable asset/horizon classes require≥200cells,≥3years,positive≥55% or negative≥55%,≥70%annual sign consistency and a year-block95%interval excluding50%. No classified subset becomes a forecast.','## Chronological persistence', 'Four inherited primary folds use the exact LOCATION01 maximum189BD origin purge and strict target maturity before the fold boundary. Test periods:2010–13,2014–17,2018–20,2021–24. Global sign uses train raw-error median; asset/horizon signs use corresponding matured train medians. Global magnitude uses train standardized median capped at±1; uncapped requests are reported.',table(pd.read_csv(OUT/'chronological_bias_persistence.csv')),'## Chronological diagnostic CRPS']
 scores=[dict(model='V5.1',ratio=1.)]+[dict(model=k,ratio=read(n)['ratio'])for k,n in zip(PREDICTIVE,['global_sign005_summary.json','asset_sign005_summary.json','horizon_sign005_summary.json','global_median_shift_summary.json'])];oro=read('bias_oracle_summary.json')['universes'];scores.append(dict(model='PERFECT_LOCATION',ratio=oro['eval']['PERFECT_CELL_LOCATION_ORACLE']['ratio']));parts.append(table(pd.DataFrame(scores)))
 parts+=['## Mathematical oracle headroom','Low-dimensional oracles minimize normalized shared-scorer CRPS with one standardized location shift per fixed group. Original scale/tails/ranks remain unchanged. Optimizer is isolated; no oracle shifts enter train bias. The perfect-cell oracle centers each original distribution on truth. Full and chronological evaluation universes are separate; captures always use the matching universe.']
 for u,items in oro.items():parts+=['### '+u,table(pd.DataFrame([dict(model=k,**v)for k,v in items.items()if isinstance(v,dict)]))]
 parts+=['## Recent-rates comparison',table(pd.DataFrame([dict(universe=k,**v)for k,v in read('recent_rates_comparison.json')['summaries'].items()]),['universe','cells','positive_fraction','mean_standardized_error','median_standardized_error']),'## Concentration and leave-one-year-out']
 con=read('episode_concentration.json')['models'];parts.append(table(pd.DataFrame([dict(model=k,largest_year_share=v['year']['largest_gross_share'],largest_year=v['year']['largest_group'],largest_era_share=v['era']['largest_gross_share'],largest_era=v['era']['largest_group'],year_concentrated=v['YEAR_CONCENTRATED'],era_concentrated=v['ERA_CONCENTRATED'])for k,v in con.items()])))
 parts+=['Shares use gross positive cell improvement, with all negative damage retained in net gain. Largest origin/asset/horizon contribution and all group shares are in episode_concentration.json. No years are dropped from primary analyses.',table(pd.read_csv(OUT/'leave_one_year_out.csv'),['excluded_year','positive_fraction','mean_standardized_error','median_standardized_error','constant_up_ratio','constant_down_ratio']),'## Rolling historical bias','Fixed1/3/5 calendar-year windows; historical origins strictly before current origin minus189BD, targets matured before current origin. Correlations are descriptive, not candidate forecasts.',table(pd.read_csv(OUT/'rolling_bias_summary.csv')),'## Negative controls']
 nc=read('negative_controls.json');parts.append(table(pd.DataFrame([dict(control=k,**v)for k,v in nc['controls'].items()])));parts+=['Seed31804;2000 permutations each. Matched random preserves actual GLOBAL positive frequency. Historical-year null shuffles train-only annual signs within fold, taking the last donor; future-fold fits are never reassigned backward. Asset/horizon nulls shuffle train-only signs. A degenerate matched null cannot establish superiority.','## Block bootstrap']
 for block,v in read('bootstrap_summary.json')['blocks'].items():parts+=['### '+block,table(pd.DataFrame([dict(metric=k,lower=w['interval_95'][0],upper=w['interval_95'][1],finite_replicates=w['finite_replicates'])for k,w in v['metrics'].items()]))]
 parts+=['5000 whole-block replicates for origin/year/asset. Full-ledger positive/mean statistics are separate from2010–2024 predictive scores/captures. Bootstrap conditions on frozen fits/oracles and cannot create independent evidence. Cross-asset common shocks and overlapping horizons remain limitations.','## Frozen decision evidence','```json\n'+json.dumps(read('final_decision.json')['gate_evidence'],indent=2)+'\n```','See headroom_decomposition.json for separate perfect, low-dimensional oracle and cross-fit predictable headroom. No favorable subset, amplitude tuning, optional source model or official score re-estimation was performed.','## Baseline protection and provenance',f"Parent RESULT:{PARENT}; parent PRE:{PARENT_PRE}; audit PRE:{verify()['PRE_RESULT_V51_BIAS04_SHA']}; main:{MAIN}. All protected parent Git files and1251 original draw caches remain unchanged. V5.1 Development0.9541 remains the previously verified reference; no submission package is modified. Final RESULT/remote verification/archive hashes are bound by external completion receipt to avoid self-referential commit hashing."]
 execution=OUT/'execution_audit.json'
 if execution.exists():parts+=['## Tests','```json\n'+json.dumps(read('execution_audit.json').get('tests',{}),indent=2)+'\n```']
 (ROOT/'V5.1-CENTER-BIAS-AUDIT-04-report.md').write_text('\n\n'.join(parts)+'\n');status('report','V5.1-CENTER-BIAS-AUDIT-04-report.md')
if __name__=='__main__':report()
