"""Executive summary: publish aggregate diagnostics; keep outcome-side cell ledgers private."""
import argparse,json
from pathlib import Path
import numpy as np,pandas as pd
from .common import *
from .decide import direction_label,source_gates,choose_axis,attribution

SOURCES=['ECB','SLOOS','SPD']
def load(private,source,stage):return json.loads((Path(private)/'partials'/source/(stage+'.json')).read_text())
def aggregate_all(private):
 pre=verify_pre(private);pieces={s:{stage:load(private,s,stage) for stage in ['metrics','curves','geometry','coefficients','bootstrap']} for s in SOURCES};gates={};attrib={};matrix=[];directions={};balances=[];magnitudes={};parts=[];extremes=[];curves=[];fixed=[];ages=[];horizons=[];years=[];coefs={};geometry={};dependence={};headroom={}
 for s,v in pieces.items():
  m=v['metrics'];c=v['curves'];g=v['geometry'];co=v['coefficients'];rows=pd.read_parquet(Path(private)/'diagnostic_inputs'/s/'ledger.parquet');gate=source_gates(m,c,g,rows);gates[s]=gate;attrib[s]=attribution(m,c,gate);directions[s]={'weighting_metrics':m['balanced'],'fold_direction':gate['direction'],'uncertainty':v['bootstrap'],'convexity_check':m['convexity']}
  balances += [dict(source=s,**x) for k,x in m['balanced'].items()];magnitudes[s]=m['magnitude'];parts+=m['partitions'];extremes+=m['extreme'];ages+=m['ages'];horizons+=m['horizons'];years += [dict(source=s,**x) for x in co['years']];coefs[s]=co;geometry[s]=g;dependence[s]=m['dependence']
  for row in c['curve']:
   (curves if row['kind']=='shrinkage' else fixed).append(row)
  cell=m['balanced']['cell'];rel=m['balanced']['release'];ratio=cell['crps_ratio'];oracle=c['oracle_ratio'];headroom[s]=dict(primary_ratio=ratio,perfect_location_ratio=oracle,mathematical_headroom=1-oracle,original_oracle_capture=(1-ratio)/(1-oracle),observed_direction=gate['direction'],observed_magnitude_calibration_slope=rel['calibration']['slope'],oracle_is_not_predictability=True)
  shr=c['sensitivity']['minimum_shrinkage'];sg=c['sensitivity']['minimum_direction_only'];stable=gate['direction']['label'] in ['MODERATE','STRONG'];low=g['by_quintile'][0];primarydamage=co['worst_year_share_of_positive_annual_damage']
  matrix.append(dict(source=s,primary_CRPS_ratio=ratio,oracle_location_ratio=oracle,oracle_capture=headroom[s]['original_oracle_capture'],Pearson=cell['pearson'],Spearman=cell['spearman'],cell_sign_accuracy=cell['sign_accuracy'],cell_balanced_sign_accuracy=cell['balanced_sign_accuracy'],release_balanced_sign_accuracy=rel['sign_accuracy'],release_balanced_balanced_sign_accuracy=rel['balanced_sign_accuracy'],release_balanced_Spearman=rel['spearman'],calibration_slope=cell['calibration']['slope'],release_calibration_slope=rel['calibration']['slope'],pred_true_magnitude_ratio=m['magnitude']['pred_true_mean_abs_ratio'],best_diagnostic_shrinkage_ratio=shr['ratio'],POST_HOC_SHRINKAGE_ARGMIN_GRID=shr['argmin_grid'],best_fixed_sign_diagnostic_ratio=sg['ratio'],fixed_sign_argmin_grid=sg['argmin_grid'],short_horizon_ratio=gate['short_ratio'],long_horizon_ratio=gate['long_ratio'],release_count=m['dependence']['unique_releases'],cells=len(rows),origins=int(rows.origin_date.nunique()),worst_year=co['worst_year'],worst_year_positive_damage_share=primarydamage,worst_year_net_damage_share=co['worst_year_share_of_net_total_damage'],coefficient_stability_mean_adjacent_cosine=co['mean_standardized_adjacent_cosine'],source_age_decay_evidence=gate['age_decay_criterion'],repeated_state_pct=m['dependence']['percentage_cells_in_releases_shared_by_multiple_origins'],DIRECTION_INFORMATION='PASS' if stable else ('WEAK' if gate['direction']['label']=='WEAK' else 'FAIL'),MAGNITUDE_CALIBRATION='PASS' if rel['calibration']['slope'] is not None and .75<=rel['calibration']['slope']<=1.25 and ratio<1 else 'FAIL',HORIZON_ALIGNMENT='FAIL' if gate['horizon_criterion'] else ('WEAK' if gate['long_ratio']>gate['short_ratio'] else 'INCONCLUSIVE'),REGIME_STABILITY='INCONCLUSIVE',RELEASE_INDEPENDENCE='WEAK',TARGET_GEOMETRY='FAIL' if gate['C'] else 'INCONCLUSIVE',label=POSTHOC,INVALID_FOR_CONFIRMATORY_USE=True))
 decision=choose_axis(gates,{s:v['curves'] for s,v in pieces.items()});central='DIRECTION_WITH_BAD_MAGNITUDE' if any(g['A'] for g in gates.values()) else ('NO_INFORMATION' if all(g['direction']['label']=='NONE' for g in gates.values()) and all(x['best_fixed_sign_diagnostic_ratio']>=1 and x['best_diagnostic_shrinkage_ratio']>=1 for x in matrix) else 'INCONCLUSIVE')
 save(OUT/'direction_signal_summary.json',{'sources':directions,'weighted_Spearman_method':'Weighted mid-CDF rank Pearson, equal total mass per origin/release/year; no IID-cell significance','fold_counts_preserved':{'ECB':5,'SLOOS':8,'SPD':5}});csv(OUT/'release_balanced_direction.csv',balances);save(OUT/'magnitude_calibration_summary.json',{'sources':magnitudes,'calibration_never_applied':True});csv(OUT/'sign_partition_summary.csv',parts);csv(OUT/'extreme_shift_contribution.csv',extremes);csv(OUT/'posthoc_shrinkage_curve.csv',curves);csv(OUT/'posthoc_direction_only_curve.csv',fixed);csv(OUT/'source_age_summary.csv',ages);csv(OUT/'horizon_failure_summary.csv',horizons);save(OUT/'release_dependence_summary.json',{'sources':dependence,'releases_are_upper_bound_not_proven_IID':True});csv(OUT/'year_regime_summary.csv',years);save(OUT/'coefficient_stability.json',{'sources':coefs,'no_refit':True,'annual_folds_do_not_identify_regimes':True});save(OUT/'target_geometry_summary.json',{'sources':geometry});csv(OUT/'cross_source_failure_matrix.csv',matrix);save(OUT/'failure_attribution.json',{'sources':attrib,'attribution_is_descriptive_not_causal':True});save(OUT/'headroom_accounting.json',{'sources':headroom});save(OUT/'next_axis_decision.json',decision);save(OUT/'bootstrap_summary.json',{'sources':{s:v['bootstrap'] for s,v in pieces.items()},'replicates_per_block':5000,'no_IID_cells':True});save(OUT/'final_decision.json',{'STUDY_COMPLETED':True,'central_conclusion':central,'next_axis':decision['next_axis'],'prior_primary_verdicts':dict.fromkeys(SOURCES,'NO'),'PRE_RESULT_INFO_FAILURE_SHA':pre,'new_models_fit':0,'new_sources_tested':0,'production_candidate':None,'official_submission_allowed':False,'independent_OOS':False,'diagnostic_transform_results_valid_for_confirmation':False,'all_primary_predictions_preserved':True,'SPD_2023_retained':True,'source_gates':gates})
 status('final_aggregation',PRE_RESULT_INFO_FAILURE_SHA=pre,new_models_fitted=0);print('FINAL DIAGNOSTIC AGGREGATION COMPLETE',central,decision['next_axis'],flush=True)
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--private',type=Path,required=True);a=ap.parse_args();aggregate_all(a.private)
