"""Executive summary: render a standalone, exposed-research failure diagnosis with evidence."""
import argparse,json
from pathlib import Path
import pandas as pd
from .common import OUT,ROOT,POSTHOC,verify_pre,status

def fmt(x,d=4):return 'N/A' if x is None or pd.isna(x) else f'{x:.{d}f}'
def table(df,columns):
 lines=['| '+' | '.join(label for _,label in columns)+' |','| '+' | '.join('---' for _ in columns)+' |']
 for _,r in df.iterrows():lines.append('| '+' | '.join(str(r[k]) if isinstance(r[k],str) else fmt(r[k]) for k,_ in columns)+' |')
 return '\n'.join(lines)
def render(private):
 pre=verify_pre(private);m=pd.read_csv(OUT/'cross_source_failure_matrix.csv');d=json.loads((OUT/'final_decision.json').read_text());dr=json.loads((OUT/'direction_signal_summary.json').read_text());co=json.loads((OUT/'coefficient_stability.json').read_text())['sources'];geo=json.loads((OUT/'target_geometry_summary.json').read_text())['sources'];attrib=json.loads((OUT/'failure_attribution.json').read_text())['sources'];parts=pd.read_csv(OUT/'sign_partition_summary.csv');cur=pd.read_csv(OUT/'posthoc_shrinkage_curve.csv');fixed=pd.read_csv(OUT/'posthoc_direction_only_curve.csv');hz=pd.read_csv(OUT/'horizon_failure_summary.csv');age=pd.read_csv(OUT/'source_age_summary.csv');decision=json.loads((OUT/'next_axis_decision.json').read_text());repro=json.loads((OUT/'prior_result_reproduction.json').read_text());ext=pd.read_csv(OUT/'extreme_shift_contribution.csv');sy=next(x for x in co['SPD']['years'] if x['year']==2023)
 text=f'''## Executive summary (read this first)

# INFORMATION-FAILURE-REASSESSMENT-01 — Why did new information fail?

Central conclusion: **{d['central_conclusion']}**. Exactly one future axis: **{d['next_axis']}**. All three prior primary verdicts remain **NO**. This study does not fit, tune, recalibrate or submit a forecasting model. It diagnoses immutable out-of-fold predictions.

## Frozen reconstruction and scope

Parent: `ca9b467d48b2fc145faa5bfe549975206c8a811f`. Diagnostic implementation PRE: `{pre}`. The PRE was pushed and remotely verified before any final diagnostic aggregation. All three primary ratios and original cell losses reproduce to 1e-12. The maximum ratio discrepancy is {max(abs(x['difference']) for x in repro['sources']):.3g}. The scorer is the recovered pinned `qfbench2-common` v2.4.3 fair ensemble CRPS; per-cell loss retains the prior past-scale normalization. No scoring formula is reimplemented.

ECB: EUR, 227 cells, five 2020–2024 annual folds, original pooled-horizon model. SLOOS: all six originally admitted UST assets, 2,616 cells, eight 2017–2024 annual folds and separate asset/horizon models. SPD: original primary UST 2Y/5Y, 552 cells, five 2020–2024 folds. Every source keeps all five horizons. These are different ledgers, not a controlled source comparison. SLOOS's original documented read-only-mask compatibility amendment did not alter scientific specification; this diagnosis never executes the prior fitting code.

The realized outcomes and complete cell ledger remain in the private recovery archive. Aggregate diagnostics are public. Missing model states are reported rather than regenerated. See lineage, reproduction and unified manifests for all prior PRE/RESULT SHAs, input hashes and schemas.

## Cross-source failure matrix

{table(m,[('source','Source'),('primary_CRPS_ratio','Primary CRPS'),('Spearman','Cell Spearman'),('cell_sign_accuracy','Cell sign accuracy'),('release_balanced_sign_accuracy','Release sign accuracy'),('release_balanced_Spearman','Release Spearman'),('calibration_slope','Cell calibration slope'),('release_calibration_slope','Release slope'),('pred_true_magnitude_ratio','Pred/true magnitude'),('best_diagnostic_shrinkage_ratio','Best diagnostic shrinkage'),('best_fixed_sign_diagnostic_ratio','Best diagnostic sign'),('worst_year','Worst year'),('worst_year_positive_damage_share','Worst share positive annual damage')])}

A sign score must be assessed with class balance and rank. A model that mostly predicts the more frequent sign can have high raw accuracy without discriminating directions. Release balancing gives each original release equal total mass; origin/year balancing are also reported. Weighted Spearman uses weighted mid-CDF ranks. No IID-cell significance is claimed. SLOOS keeps eight folds: the 4/5 and 3/5 descriptive rules scale to 7/8 and 5/8.

'''
 for s in ['ECB','SLOOS','SPD']:
  rel=dr['sources'][s]['weighting_metrics']['release'];fold=dr['sources'][s]['fold_direction'];boot=dr['sources'][s]['uncertainty']['blocks'];text+=f"### {s}: direction and uncertainty\n\nDirection label **{fold['label']}**; positive release-balanced direction/rank in {fold['positive_folds']}/{fold['evaluable_folds']} original folds. Release accuracy {fmt(rel['sign_accuracy'])}, balanced accuracy {fmt(rel['balanced_sign_accuracy'])}, positive-truth share {fmt(rel['positive_truth_fraction'])}, Spearman {fmt(rel['spearman'])}. Release-block 95% accuracy CI {boot['release']['direction_95ci']['release_sign_accuracy']}; Spearman CI {boot['release']['direction_95ci']['release_spearman']}. Year-block Spearman CI {boot['year']['direction_95ci']['release_spearman']}. There are {boot['release']['blocks']} release blocks and {boot['year']['blocks']} year blocks, with 5,000 paired replicates each. These intervals describe an exposed fixed-prediction ledger, not refit uncertainty or independent validation.\n\n"
 text+='## Sign-correct versus sign-wrong damage\n\n'+table(parts[(parts.dimension=='all')&(parts.balance=='cell')],[('source','Source'),('partition','Partition'),('fraction_cells','Cell fraction'),('crps_ratio','CRPS ratio'),('harmed_fraction','Harmed fraction'),('overshoot_fraction','Overshoot fraction'),('fraction_total_net_damage','Net damage share')])+'\n\nThe release-balanced, horizon and year partitions remain in sign_partition_summary.csv. Release fractions are nonexclusive: one release can contain both correct and wrong signs. A correct-direction pure translation cannot worsen convex location CRPS while it stays between the original median and truth. Sign-correct damage therefore implicates overshooting, rather than failure of the CRPS formula. No sign-defined subset becomes a primary result.\n\n'
 text+='## Magnitude and fixed diagnostic translations\n\nPost-hoc OLS and Theil-Sen calibration are descriptive only, never applied. The entire frozen prediction is multiplied by the universal grid; a separate curve uses only its sign and fixed SD units. Each point is **POST_HOC_DIAGNOSTIC_ONLY / INVALID_FOR_CONFIRMATORY_USE**. A favorable exposed minimum cannot rescue a prior NO. No interpolation or source-specific search occurs.\n\n'+table(cur,[('source','Source'),('value','Lambda'),('crps_ratio','Diagnostic CRPS'),('robust_to_one_year_and_release','Leave-one-block gain robust')])+'\n\n'+table(fixed,[('source','Source'),('value','Fixed sign SD shift'),('crps_ratio','Diagnostic CRPS'),('sign_correct_crps_ratio','Correct-sign diagnostic ratio'),('robust_to_one_year_and_release','Gain not one block')])+'\n\n'+table(ext,[('source','Source'),('top_fraction','Top absolute-shift fraction'),('share_total_net_damage','Net damage share'),('share_gross_positive_damage','Gross damage share')])+'\n\nAll rows stay in the main ledger. Sensitivity omits one existing block only to diagnose concentration, never to produce a new model or favorable main result. A diagnostic gain is called nonconcentrated only if every leave-one-release and leave-one-year ratio remains below 1 and no one block contributes more than half of gross positive block gains.\n\n'
 text+=f'''## SPD 2023 retained: failure mechanism

2023 accounts for {fmt(co['SPD']['worst_year_share_of_positive_annual_damage'])} of positive annual net damage and {fmt(co['SPD']['worst_year_share_of_net_total_damage'])} of total net damage. Its release-balanced CRPS ratio is {fmt(sy['release_balanced_metrics']['crps_ratio'])}, sign accuracy {fmt(sy['release_balanced_metrics']['sign_accuracy'])}, Spearman {fmt(sy['release_balanced_metrics']['spearman'])}, and calibration slope {fmt(sy['release_balanced_metrics']['calibration']['slope'])}. Sign-correct harmed fraction {fmt(sy['sign_correct_harmed_fraction'])}, sign-correct overshoot fraction {fmt(sy['sign_correct_overshoot_fraction'])}.

Held-out source extremeness is measured against each preserved original train scaler: mean max absolute z {fmt(sy['mean_max_abs_train_z'])}, p95 {fmt(sy['p95_max_abs_train_z'])}, max {fmt(sy['max_train_z'])}; fraction above 3 is {fmt(sy['fraction_heldout_cells_max_z_gt3'])}. Mean absolute predicted raw shift {fmt(sy['mean_abs_raw_shift'])}, actual raw error {fmt(sy['mean_abs_raw_error'])}, baseline SD {fmt(sy['mean_SD'])}. The five mean absolute linear feature contributions are {sy['mean_abs_prediction_component_by_feature']}, in the frozen SPD feature order. This separates direction, amplitude and source extrapolation; it is not evidence that a newly invented 2023 regime should be excluded.

## Source age and horizon alignment

'''+table(hz[hz.balance=='release'],[('source','Source'),('group','Horizon'),('crps_ratio','Release CRPS'),('sign_accuracy','Sign accuracy'),('spearman','Spearman'),('calibration_slope','Calibration slope'),('mean_abs_predicted_delta','Pred |delta|'),('mean_abs_true_delta','True |delta|')])+'\n\n'+table(age[age.balance=='release'],[('source','Source'),('age_bin','Business-day age'),('cells','Cells'),('releases','Releases'),('crps_ratio','Release CRPS'),('sign_accuracy','Sign accuracy'),('spearman','Spearman')])+'\n\nAge and short/long-horizon criteria are frozen in experiment_spec.json. They are hypotheses, not tuned cutoffs or proposed favorable subsets. Sparse and inactive bins remain visible.\n\n## Repeated releases, coefficients and target geometry\n\n'
 for _,row in m.iterrows():
  s=row.source;gs=geo[s];text+=f"{s}: {int(row.cells)} cells, {int(row.origins)} origins, {int(row.release_count)} unique releases; {row.repeated_state_pct:.1f}% of cells share a release across multiple origins. Adjacent original standardized coefficient cosine mean {fmt(row.coefficient_stability_mean_adjacent_cosine)}. Lowest within-asset/horizon SD quintile gross positive damage share {fmt(gs['by_quintile'][0]['gross_positive_damage_share'])}; raw vs standardized release Spearman {fmt(gs['release_balanced_raw']['spearman'])} vs {fmt(gs['release_balanced_standardized']['spearman'])}.\n\n"
 text+='The full SD-quintile table and held-out scaler diagnostics are preserved. Positive SD makes raw and standardized direction exactly identical. For a fixed standardized prediction, a smaller baseline SD makes the raw shift smaller, not larger. Small SD may inflate original normalized training targets; these diagnostics cannot establish that causal training mechanism without a separately frozen study. The past normalization scale in CRPS is a different quantity. Annual coefficients can be unstable without proving a pre-outcome regime rule. No pre-existing regime variables sufficient for AXIS D were recovered.\n\n## Failure attribution, headroom and one next axis\n\n'
 for s,a in attrib.items():text+=f"{s}: **{a['primary_failure_mode']}**. Quantitative evidence: `{a['quantitative_evidence']}`. Secondary contributors: {a['secondary_contributors']}. Attribution is descriptive rather than causal.\n\n"
 text+=f"**{d['central_conclusion']}**. {decision['reason']} Next: **{d['next_axis']}**, and nothing else is selected or executed. Gate-by-gate evidence is in next_axis_decision.json. Large perfect-location oracle headroom is mathematical possibility, not evidence that source information predicts that error.\n\n## Limits and verification\n\nAll outcomes were previously exposed. No independent OOS claim, new alpha, new official score or submission follows. Diagnostic minimum selection and many descriptive comparisons are outcome-exposed and can overfit. Different source assets/origin counts prevent causal cross-source ranking. Release and annual blocks are few and correlated; 5,000 resamples do not create new information events. Source states can repeat across many cells; source_age changes within a packet. Bootstrap holds predictions fixed. No prior model is retrained. Every prior prediction file, draw array and input hash is checked before aggregation. 2023 stays in all primary SPD diagnostics. Research-specific, affected, full repository and common-toolkit test receipts, Git lineage, protected main SHA and recovery verification are recorded in execution_audit.json and the private completion receipt.\n"
 (ROOT/'INFORMATION-FAILURE-REASSESSMENT-01-report.md').write_text(text);status('report');print('REPORT complete',flush=True)
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--private',type=Path,required=True);a=ap.parse_args();render(a.private)
